### ISSUE TITLE
[BUG]  no hud on D&D 

### ISSUE THREAD

**Issue by raveguy12** [Larkinabout/fvtt-token-action-hud-dnd5e#124]
no hud shown in foundry for dm or pc on D&D 5e 4..0.4 is this cause of the verison of foundry even though its compatible and loaded?

**Comment by Larkinabout** [comment]
Ah, yeah, that's me using a core utility that doesn't actually exist in the released version yet.

**Comment by Larkinabout** [comment]
Fixed the `capitalize` error in 1.6.4.

**Comment by raveguy12** [comment]
An error that is showing in console is
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'name')
[Detected 2 packages: token-action-hud-dnd5e(1.6.4), token-action-hud-core(1.5.7)]
    at #k (action-handler.js:1244:51)
    at action-handler.js:300:31
    at async Promise.all (index 0)
    at async #o (action-handler.js:287:13)
    at async Promise.all (index 0)
    at async #i (action-handler.js:88:11)
    at async ActionHandler.buildSystemActions (action-handler.js:65:11)
    at async #h (action-handler.js:208:72)
    at async Promise.all (index 0)
    at async ActionHandler.buildHud (action-handler.js:98:31)
    at async #It (token-action-hud.js:1157:14)
    at async TokenActionHud.update (token-action-hud.js:1093:20)

and still not displaying a HUD running foundry 331 and D&D 4.0.4
