### ISSUE TITLE
[BUG] Console log Error CONFIG.DND5E.abilities

### ISSUE THREAD

**Issue by yaWgnorW** [Larkinabout/fvtt-token-action-hud-dnd5e#64]
Upon updating to the latest version of DnD5e 2.3, I noticed a high volume of Error flags being generated when going to the Action HUD for any actor. Repeatable each time. Does not break any features we've been able to identify with very minimal interaction, just providing details here.

Error details:
Error: The value of CONFIG.DND5E.abilities has been changed to an object. The former value can be accessed from .label.
Deprecated since Version 2.2
Backwards-compatible support will be removed in Version 2.4
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Object.toString (config.mjs:1905:19)
    at token-action-hud-dnd5e.min.js:1:15078
    at Array.map (<anonymous>)
    at #p (token-action-hud-dnd5e.min.js:1:14824)
    at #i (token-action-hud-dnd5e.min.js:1:14228)
    at async ActionHandler.buildSystemActions (token-action-hud-dnd5e.min.js:1:13981)
    at async #h (action-handler.js:206:72)
    at async Promise.all (index 0)
    at async ActionHandler.buildHud (action-handler.js:96:31)
    at async #Ct (token-action-hud.js:1056:14)
    at async TokenActionHud.update (token-action-hud.js:992:20)

**Steps to reproduce**
1. Update DnD 5e 2.3
2. Load and select actor, go to overlay

**Versions:**
- Token Action HUD Core: [1.4.18]
- Token Action HUD System: [D&D 5e 1.4.10]
- System: [e.g. dnd5e 2.4]
- Foundry VTT: [e.g. V10 Build 303
- Browser: [e.g. Google Chrome 115.0.5790.171]

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.4.11.
