### ISSUE TITLE
[BUG] When selecting NPC, no HUD for NPC with Custom Label: "Custom" and then freezes HUD on last display

### ISSUE THREAD

**Issue by the-real-orson** [Larkinabout/fvtt-token-action-hud-dnd5e#86]
**Describe the bug**
Whether HUD is displaying already or not, edit: once an NPC which has the Custom Label 'Custom' is selected, the HUD just remains in current state and does not change to the selected NPC, nor will it change with subsequent changes in token selection.

**Versions:**
- Token Action HUD Core: 1.5.4
- Token Action HUD System: 1.5.4
- System: DnD5e 3.1.2
- Foundry VTT: 11.315
- Browser: Google Chrome 123.0.6312.123 (Official Build) (64-bit)

**Additional context**
Any additional context.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
    at token-action-hud-dnd5e.min.js:1:15189
    at Array.map (<anonymous>)
    at #p (token-action-hud-dnd5e.min.js:1:15056)
    at #i (token-action-hud-dnd5e.min.js:1:14440)
    at async ActionHandler.buildSystemActions (token-action-hud-dnd5e.min.js:1:14193)
    at async #h (action-handler.js:208:72)
    at async Promise.all (index 0)
    at async ActionHandler.buildHud (action-handler.js:98:31)
    at async #It (token-action-hud.js:1157:14)
    at async TokenActionHud.update (token-action-hud.js:1093:20)

**Comment by the-real-orson** [comment]
I'm having trouble reproducing this error. I changed the Custom Label to a blank field and now I can't reproduce the error by putting 'Custom' back in the field.  Perhaps there was something corrupted in the actor...dunno, I'll keep an eye out for it in the future.
